# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_slider = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_slider.sizePolicy().hasHeightForWidth())
        self.frame_slider.setSizePolicy(sizePolicy)
        self.frame_slider.setStyleSheet("QFrame{\n"
                                        "    background-color:rgb(220, 228, 243)\n"
                                        "}")
        self.frame_slider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider.setObjectName("frame_slider")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_slider)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_home = QtWidgets.QPushButton(self.frame_slider)
        self.pushButton_home.setStyleSheet("QPushButton{\n"
                                           "    border-style: solid;\n"
                                           "    border-top-color: transparent;\n"
                                           "    border-right-color: transparent;\n"
                                           "    border-left-color: transparent;\n"
                                           "    border-bottom-color: transparent;\n"
                                           "    border-width: 1px;\n"
                                           "    border-style: solid;\n"
                                           "    color:rgb(242, 250, 253);\n"
                                           "    padding: 2px;\n"
                                           "    background-color:#60669B;\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "    border-style: solid;\n"
                                           "    border-top-color: transparent;\n"
                                           "    border-right-color: transparent;\n"
                                           "    border-left-color: transparent;\n"
                                           "    border-bottom-width: 1px;\n"
                                           "    border-style: solid;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    padding-bottom: 2px;\n"
                                           "    background-color: #3498DB;\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "       background-color: #2980B9;\n"
                                           "       border-color: #007bff;\n"
                                           " }")
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout.addWidget(self.pushButton_home)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_clac = QtWidgets.QPushButton(self.frame_slider)
        self.pushButton_clac.setStyleSheet("QPushButton{\n"
                                           "    border-style: solid;\n"
                                           "    border-top-color: transparent;\n"
                                           "    border-right-color: transparent;\n"
                                           "    border-left-color: transparent;\n"
                                           "    border-bottom-color: transparent;\n"
                                           "    border-width: 1px;\n"
                                           "    border-style: solid;\n"
                                           "    color:rgb(242, 250, 253);\n"
                                           "    padding: 2px;\n"
                                           "    background-color:#60669B\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "    border-style: solid;\n"
                                           "    border-top-color: transparent;\n"
                                           "    border-right-color: transparent;\n"
                                           "    border-left-color: transparent;\n"
                                           "    border-bottom-width: 1px;\n"
                                           "    border-style: solid;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    padding-bottom: 2px;\n"
                                           "    background-color: #3498DB;\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "       background-color: #2980B9;\n"
                                           "       border-color: #007bff;\n"
                                           " }")
        self.pushButton_clac.setObjectName("pushButton_clac")
        self.verticalLayout.addWidget(self.pushButton_clac)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_plan = QtWidgets.QPushButton(self.frame_slider)
        self.pushButton_plan.setStyleSheet("QPushButton{\n"
                                           "    border-style: solid;\n"
                                           "    border-top-color: transparent;\n"
                                           "    border-right-color: transparent;\n"
                                           "    border-left-color: transparent;\n"
                                           "    border-bottom-color: transparent;\n"
                                           "    border-width: 1px;\n"
                                           "    border-style: solid;\n"
                                           "    color:rgb(242, 250, 253);\n"
                                           "    padding: 2px;\n"
                                           "    background-color:#60669B\n"
                                           "}\n"
                                           "QPushButton:hover{\n"
                                           "    border-style: solid;\n"
                                           "    border-top-color: transparent;\n"
                                           "    border-right-color: transparent;\n"
                                           "    border-left-color: transparent;\n"
                                           "    border-bottom-width: 1px;\n"
                                           "    border-style: solid;\n"
                                           "    color: rgb(255, 255, 255);\n"
                                           "    padding-bottom: 2px;\n"
                                           "    background-color: #3498DB;\n"
                                           "}\n"
                                           "QPushButton:pressed {\n"
                                           "       background-color: #2980B9;\n"
                                           "       border-color: #007bff;\n"
                                           " }")
        self.pushButton_plan.setObjectName("pushButton_plan")
        self.verticalLayout.addWidget(self.pushButton_plan)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_movement = QtWidgets.QPushButton(self.frame_slider)
        self.pushButton_movement.setStyleSheet("QPushButton{\n"
                                               "    border-style: solid;\n"
                                               "    border-top-color: transparent;\n"
                                               "    border-right-color: transparent;\n"
                                               "    border-left-color: transparent;\n"
                                               "    border-bottom-color: transparent;\n"
                                               "    border-width: 1px;\n"
                                               "    border-style: solid;\n"
                                               "    color:rgb(242, 250, 253);\n"
                                               "    padding: 2px;\n"
                                               "    background-color:#60669B\n"
                                               "}\n"
                                               "QPushButton:hover{\n"
                                               "    border-style: solid;\n"
                                               "    border-top-color: transparent;\n"
                                               "    border-right-color: transparent;\n"
                                               "    border-left-color: transparent;\n"
                                               "    border-bottom-width: 1px;\n"
                                               "    border-style: solid;\n"
                                               "    color: rgb(255, 255, 255);\n"
                                               "    padding-bottom: 2px;\n"
                                               "    background-color: #3498DB;\n"
                                               "}\n"
                                               "QPushButton:pressed {\n"
                                               "       background-color: #2980B9;\n"
                                               "       border-color: #007bff;\n"
                                               " }")
        self.pushButton_movement.setObjectName("pushButton_movement")
        self.verticalLayout.addWidget(self.pushButton_movement)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_prevent = QtWidgets.QPushButton(self.frame_slider)
        self.pushButton_prevent.setStyleSheet("QPushButton{\n"
                                              "    border-style: solid;\n"
                                              "    border-top-color: transparent;\n"
                                              "    border-right-color: transparent;\n"
                                              "    border-left-color: transparent;\n"
                                              "    border-bottom-color: transparent;\n"
                                              "    border-width: 1px;\n"
                                              "    border-style: solid;\n"
                                              "    color:rgb(242, 250, 253);\n"
                                              "    padding: 2px;\n"
                                              "    background-color:#60669B\n"
                                              "}\n"
                                              "QPushButton:hover{\n"
                                              "    border-style: solid;\n"
                                              "    border-top-color: transparent;\n"
                                              "    border-right-color: transparent;\n"
                                              "    border-left-color: transparent;\n"
                                              "    border-bottom-width: 1px;\n"
                                              "    border-style: solid;\n"
                                              "    color: rgb(255, 255, 255);\n"
                                              "    padding-bottom: 2px;\n"
                                              "    background-color: #3498DB;\n"
                                              "}\n"
                                              "QPushButton:pressed {\n"
                                              "       background-color: #2980B9;\n"
                                              "       border-color: #007bff;\n"
                                              " }")
        self.pushButton_prevent.setObjectName("pushButton_prevent")
        self.verticalLayout.addWidget(self.pushButton_prevent)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame_slider)
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_content.sizePolicy().hasHeightForWidth())
        self.frame_content.setSizePolicy(sizePolicy)
        self.frame_content.setStyleSheet("QFrame{\n"
                                         "    background-color:rgb(255, 255, 255)\n"
                                         "}")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("QFrame{\n"
                                         "    background-color: #EEF1F7\n"
                                         "}")
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_home.sizePolicy().hasHeightForWidth())
        self.page_home.setSizePolicy(sizePolicy)
        self.page_home.setObjectName("page_home")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_home = QtWidgets.QFrame(self.page_home)
        self.frame_home.setStyleSheet("QFrame{\n"
                                      "    background-color: #EEF1F7\n"
                                      "}")
        self.frame_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home.setObjectName("frame_home")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_home)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_home_power = QtWidgets.QFrame(self.frame_home)
        self.frame_home_power.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_power.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_power.setObjectName("frame_home_power")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_home_power)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.label = QtWidgets.QLabel(self.frame_home_power)
        self.label.setStyleSheet("QLabel {\n"
                                 "    text-align: center; /* 文本居中对齐 */\n"
                                 "    border: 1px solid black; /* 可选，添加边框以查看圆形效果 */\n"
                                 "    min-width:  100px;\n"
                                 "    max-width:  100px;\n"
                                 "    min-height: 100px;\n"
                                 "    max-height: 100px;\n"
                                 "    border-radius: 50px;\n"
                                 "    background-color: rgb(255, 255, 255);\n"
                                 "}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_14.addWidget(self.frame_home_power)
        self.frame_home_record = QtWidgets.QFrame(self.frame_home)
        self.frame_home_record.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_record.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_record.setObjectName("frame_home_record")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_home_record)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.tableWidget_physical = QtWidgets.QTableWidget(self.frame_home_record)
        self.tableWidget_physical.setStyleSheet("/*表格的一种美化方式*/\n"
                                                "QHeaderView\n"
                                                "{\n"
                                                "    background:transparent;\n"
                                                "}\n"
                                                "\n"
                                                "QHeaderView::section\n"
                                                "{\n"
                                                "    font-size:14px;\n"
                                                "    font-family:\"Microsoft YaHei\";\n"
                                                "    color:#FFFFFF;\n"
                                                "    background:#60669B;\n"
                                                "    border:none;\n"
                                                "    text-align:left;\n"
                                                "}\n"
                                                "\n"
                                                "QTableWidget\n"
                                                "{\n"
                                                "    background:#FFFFFF;\n"
                                                "    border:none;\n"
                                                "\n"
                                                "    font-size:20px;\n"
                                                "    font-family:\"Microsoft YaHei\";\n"
                                                "    color:#666666;\n"
                                                "}\n"
                                                "QTableWidget::item\n"
                                                "{\n"
                                                "    border-bottom:1px solid #EEF1F7 ;\n"
                                                "}\n"
                                                "\n"
                                                "QTableWidget::item::selected\n"
                                                "{\n"
                                                "    color:red;\n"
                                                "    background:#EFF4FF;\n"
                                                "}\n"
                                                "QScrollBar::handle:vertical\n"
                                                "{\n"
                                                "    background: rgba(255,255,255,20%);\n"
                                                "    border: 0px solid grey;\n"
                                                "    border-radius:1px;\n"
                                                "    width: 2px;\n"
                                                "}\n"
                                                "\n"
                                                "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                                                "{\n"
                                                "    background:rgba(255,255,255,10%);\n"
                                                "}\n"
                                                "\n"
                                                "\n"
                                                "QScollBar::add-line:vertical, QScrollBar::sub-line:vertical\n"
                                                "{\n"
                                                "    background:transparent;\n"
                                                "}\n"
                                                "")
        self.tableWidget_physical.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_physical.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget_physical.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_physical.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_physical.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget_physical.setAutoScroll(True)
        self.tableWidget_physical.setAlternatingRowColors(False)
        self.tableWidget_physical.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_physical.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_physical.setObjectName("tableWidget_physical")
        self.tableWidget_physical.setColumnCount(9)
        self.tableWidget_physical.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_physical.setHorizontalHeaderItem(8, item)
        self.tableWidget_physical.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_physical.horizontalHeader().setMinimumSectionSize(10)
        self.tableWidget_physical.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_physical.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_physical.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_15.addWidget(self.tableWidget_physical)
        self.tableWidget_sports = QtWidgets.QTableWidget(self.frame_home_record)
        self.tableWidget_sports.setStyleSheet("/*表格的一种美化方式*/\n"
                                              "QHeaderView\n"
                                              "{\n"
                                              "    background:transparent;\n"
                                              "}\n"
                                              "\n"
                                              "QHeaderView::section\n"
                                              "{\n"
                                              "    font-size:14px;\n"
                                              "    font-family:\"Microsoft YaHei\";\n"
                                              "    color:#FFFFFF;\n"
                                              "    background:#60669B;\n"
                                              "    border:none;\n"
                                              "    text-align:left;\n"
                                              "}\n"
                                              "\n"
                                              "QTableWidget\n"
                                              "{\n"
                                              "    background:#FFFFFF;\n"
                                              "    border:none;\n"
                                              "\n"
                                              "    font-size:20px;\n"
                                              "    font-family:\"Microsoft YaHei\";\n"
                                              "    color:#666666;\n"
                                              "}\n"
                                              "QTableWidget::item\n"
                                              "{\n"
                                              "    border-bottom:1px solid #EEF1F7 ;\n"
                                              "}\n"
                                              "\n"
                                              "QTableWidget::item::selected\n"
                                              "{\n"
                                              "    color:red;\n"
                                              "    background:#EFF4FF;\n"
                                              "}\n"
                                              "QScrollBar::handle:vertical\n"
                                              "{\n"
                                              "    background: rgba(255,255,255,20%);\n"
                                              "    border: 0px solid grey;\n"
                                              "    border-radius:1px;\n"
                                              "    width: 2px;\n"
                                              "}\n"
                                              "\n"
                                              "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                                              "{\n"
                                              "    background:rgba(255,255,255,10%);\n"
                                              "}\n"
                                              "\n"
                                              "\n"
                                              "QScollBar::add-line:vertical, QScrollBar::sub-line:vertical\n"
                                              "{\n"
                                              "    background:transparent;\n"
                                              "}\n"
                                              "")
        self.tableWidget_sports.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sports.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_sports.setObjectName("tableWidget_sports")
        self.tableWidget_sports.setColumnCount(7)
        self.tableWidget_sports.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_sports.setHorizontalHeaderItem(6, item)
        self.verticalLayout_15.addWidget(self.tableWidget_sports)
        self.verticalLayout_14.addWidget(self.frame_home_record)
        self.verticalLayout_3.addWidget(self.frame_home)
        self.stackedWidget.addWidget(self.page_home)
        self.page_clac = QtWidgets.QWidget()
        self.page_clac.setObjectName("page_clac")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_clac)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_clac = QtWidgets.QFrame(self.page_clac)
        self.frame_clac.setStyleSheet("QFrame{\n"
                                      "    background-color: #EEF1F7\n"
                                      "}")
        self.frame_clac.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clac.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clac.setObjectName("frame_clac")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_clac)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_conversaion = QtWidgets.QPushButton(self.frame_clac)
        self.pushButton_conversaion.setStyleSheet("QPushButton {\n"
                                                  "    color:rgb(242, 250, 253);\n"
                                                  "    border-radius: 8px;\n"
                                                  "    padding: 10px 15px;\n"
                                                  "}\n"
                                                  "QPushButton:pressed {\n"
                                                  "    background-color: #D8D8FA;\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton {\n"
                                                  "    background-color:#60669B;\n"
                                                  "}\n"
                                                  "\n"
                                                  "QPushButton:pressed {\n"
                                                  "    background-color: #B0E0E6;\n"
                                                  "}")
        self.pushButton_conversaion.setObjectName("pushButton_conversaion")
        self.verticalLayout_6.addWidget(self.pushButton_conversaion)
        self.pushButton_forecast = QtWidgets.QPushButton(self.frame_clac)
        self.pushButton_forecast.setStyleSheet("QPushButton {\n"
                                               "    color:rgb(242, 250, 253);\n"
                                               "    border-radius: 8px;\n"
                                               "    padding: 10px 15px;\n"
                                               "}\n"
                                               "QPushButton:pressed {\n"
                                               "    background-color: #D8D8FA;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton {\n"
                                               "    background-color:#60669B;\n"
                                               "}\n"
                                               "\n"
                                               "QPushButton:pressed {\n"
                                               "    background-color: #B0E0E6;\n"
                                               "}")
        self.pushButton_forecast.setObjectName("pushButton_forecast")
        self.verticalLayout_6.addWidget(self.pushButton_forecast)
        self.verticalLayout_5.addWidget(self.frame_clac)
        self.stackedWidget.addWidget(self.page_clac)
        self.page_plan = QtWidgets.QWidget()
        self.page_plan.setObjectName("page_plan")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_plan)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_plan = QtWidgets.QFrame(self.page_plan)
        self.frame_plan.setStyleSheet("QFrame{\n"
                                      "    background-color: #EEF1F7\n"
                                      "}")
        self.frame_plan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plan.setObjectName("frame_plan")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_plan)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_generate_plan = QtWidgets.QPushButton(self.frame_plan)
        self.pushButton_generate_plan.setStyleSheet("QPushButton {\n"
                                                    "    color:rgb(242, 250, 253);\n"
                                                    "    border-radius: 8px;\n"
                                                    "    padding: 10px 15px;\n"
                                                    "}\n"
                                                    "QPushButton:pressed {\n"
                                                    "    background-color: #D8D8FA;\n"
                                                    "}\n"
                                                    "\n"
                                                    "QPushButton {\n"
                                                    "   background-color:#60669B;\n"
                                                    "}\n"
                                                    "\n"
                                                    "QPushButton:pressed {\n"
                                                    "    background-color: #B0E0E6;\n"
                                                    "}")
        self.pushButton_generate_plan.setObjectName("pushButton_generate_plan")
        self.verticalLayout_4.addWidget(self.pushButton_generate_plan)
        self.verticalLayout_7.addWidget(self.frame_plan)
        self.stackedWidget.addWidget(self.page_plan)
        self.page_movement = QtWidgets.QWidget()
        self.page_movement.setObjectName("page_movement")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_movement)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.page_movement)
        self.scrollArea.setStyleSheet("QWidget {\n"
                                      "    background-color: #EEF1F7 ;\n"
                                      "    border:none\n"
                                      "}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 475, 318))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_movement)
        self.page_prevent = QtWidgets.QWidget()
        self.page_prevent.setObjectName("page_prevent")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_prevent)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea_prevent = QtWidgets.QScrollArea(self.page_prevent)
        self.scrollArea_prevent.setStyleSheet("QWidget {\n"
                                              "    background-color: #EEF1F7 ;\n"
                                              "    border:none\n"
                                              "}")
        self.scrollArea_prevent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_prevent.setWidgetResizable(True)
        self.scrollArea_prevent.setObjectName("scrollArea_prevent")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 475, 318))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_prevent.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea_prevent)
        self.stackedWidget.addWidget(self.page_prevent)
        self.page_convert = QtWidgets.QWidget()
        self.page_convert.setObjectName("page_convert")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_convert)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_convert = QtWidgets.QFrame(self.page_convert)
        self.frame_convert.setStyleSheet("QFrame{\n"
                                         "    background-color: #EEF1F7\n"
                                         "}")
        self.frame_convert.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_convert.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_convert.setObjectName("frame_convert")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_convert)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_convert_must = QtWidgets.QFrame(self.frame_convert)
        self.frame_convert_must.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_convert_must.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_convert_must.setObjectName("frame_convert_must")
        self.formLayout = QtWidgets.QFormLayout(self.frame_convert_must)
        self.formLayout.setContentsMargins(9, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_distance = QtWidgets.QLabel(self.frame_convert_must)
        self.label_distance.setObjectName("label_distance")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_distance)
        self.comboBox_distance = QtWidgets.QComboBox(self.frame_convert_must)
        self.comboBox_distance.setEditable(True)
        self.comboBox_distance.setObjectName("comboBox_distance")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.setItemText(0, "")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.comboBox_distance.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_distance)
        self.label_time = QtWidgets.QLabel(self.frame_convert_must)
        self.label_time.setObjectName("label_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_time)
        self.timeEdit_time = QtWidgets.QTimeEdit(self.frame_convert_must)
        self.timeEdit_time.setObjectName("timeEdit_time")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit_time)
        self.label_speed = QtWidgets.QLabel(self.frame_convert_must)
        self.label_speed.setObjectName("label_speed")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_speed)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.frame_convert_must)
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_speed)
        self.label_unit = QtWidgets.QLabel(self.frame_convert_must)
        self.label_unit.setObjectName("label_unit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_unit)
        self.radioButton_pace = QtWidgets.QRadioButton(self.frame_convert_must)
        self.radioButton_pace.setObjectName("radioButton_pace")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radioButton_pace)
        self.radioButton_hourSpeed = QtWidgets.QRadioButton(self.frame_convert_must)
        self.radioButton_hourSpeed.setObjectName("radioButton_hourSpeed")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.radioButton_hourSpeed)
        self.radioButton_lapSpeed = QtWidgets.QRadioButton(self.frame_convert_must)
        self.radioButton_lapSpeed.setObjectName("radioButton_lapSpeed")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.radioButton_lapSpeed)
        self.frame_divisionLine = QtWidgets.QFrame(self.frame_convert_must)
        self.frame_divisionLine.setStyleSheet("QFrame{\n"
                                              "    color: rgb(96, 102, 155);\n"
                                              "    background-color: rgb(96, 102, 155);\n"
                                              "}")
        self.frame_divisionLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_divisionLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_divisionLine.setObjectName("frame_divisionLine")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.frame_divisionLine)
        self.label_pace = QtWidgets.QLabel(self.frame_convert_must)
        self.label_pace.setObjectName("label_pace")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_pace)
        self.lineEdit_pace = QtWidgets.QLineEdit(self.frame_convert_must)
        self.lineEdit_pace.setObjectName("lineEdit_pace")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pace)
        self.label_hourSpeed = QtWidgets.QLabel(self.frame_convert_must)
        self.label_hourSpeed.setObjectName("label_hourSpeed")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_hourSpeed)
        self.lineEdit_hourSpeed = QtWidgets.QLineEdit(self.frame_convert_must)
        self.lineEdit_hourSpeed.setReadOnly(True)
        self.lineEdit_hourSpeed.setObjectName("lineEdit_hourSpeed")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_hourSpeed)
        self.label_lapSpeed = QtWidgets.QLabel(self.frame_convert_must)
        self.label_lapSpeed.setObjectName("label_lapSpeed")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_lapSpeed)
        self.lineEdit_lapSpeed = QtWidgets.QLineEdit(self.frame_convert_must)
        self.lineEdit_lapSpeed.setReadOnly(True)
        self.lineEdit_lapSpeed.setObjectName("lineEdit_lapSpeed")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_lapSpeed)
        self.pushButton_confirm_convert = QtWidgets.QPushButton(self.frame_convert_must)
        self.pushButton_confirm_convert.setObjectName("pushButton_confirm_convert")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.pushButton_confirm_convert)
        self.verticalLayout_13.addWidget(self.frame_convert_must)
        self.verticalLayout_10.addWidget(self.frame_convert)
        self.stackedWidget.addWidget(self.page_convert)
        self.page_forecast_1 = QtWidgets.QWidget()
        self.page_forecast_1.setObjectName("page_forecast_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_forecast_1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_forecast = QtWidgets.QFrame(self.page_forecast_1)
        self.frame_forecast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_forecast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_forecast.setObjectName("frame_forecast")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_forecast)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_tips = QtWidgets.QLabel(self.frame_forecast)
        self.label_tips.setObjectName("label_tips")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_tips)
        self.label_1km = QtWidgets.QLabel(self.frame_forecast)
        self.label_1km.setObjectName("label_1km")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_1km)
        self.timeEdit_1km = QtWidgets.QTimeEdit(self.frame_forecast)
        self.timeEdit_1km.setObjectName("timeEdit_1km")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit_1km)
        self.label_3km = QtWidgets.QLabel(self.frame_forecast)
        self.label_3km.setObjectName("label_3km")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3km)
        self.timeEdit_3km = QtWidgets.QTimeEdit(self.frame_forecast)
        self.timeEdit_3km.setObjectName("timeEdit_3km")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeEdit_3km)
        self.label_5km = QtWidgets.QLabel(self.frame_forecast)
        self.label_5km.setObjectName("label_5km")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5km)
        self.timeEdit_5km = QtWidgets.QTimeEdit(self.frame_forecast)
        self.timeEdit_5km.setObjectName("timeEdit_5km")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeEdit_5km)
        self.label_10km = QtWidgets.QLabel(self.frame_forecast)
        self.label_10km.setObjectName("label_10km")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10km)
        self.timeEdit_10km = QtWidgets.QTimeEdit(self.frame_forecast)
        self.timeEdit_10km.setObjectName("timeEdit_10km")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timeEdit_10km)
        self.label_halfMarathon = QtWidgets.QLabel(self.frame_forecast)
        self.label_halfMarathon.setObjectName("label_halfMarathon")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_halfMarathon)
        self.timeEdit_halfMarathon = QtWidgets.QTimeEdit(self.frame_forecast)
        self.timeEdit_halfMarathon.setObjectName("timeEdit_halfMarathon")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.timeEdit_halfMarathon)
        self.label_marathon = QtWidgets.QLabel(self.frame_forecast)
        self.label_marathon.setObjectName("label_marathon")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_marathon)
        self.timeEdit_marathon = QtWidgets.QTimeEdit(self.frame_forecast)
        self.timeEdit_marathon.setObjectName("timeEdit_marathon")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.timeEdit_marathon)
        self.pushButton_confirm = QtWidgets.QPushButton(self.frame_forecast)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_confirm)
        self.verticalLayout_11.addWidget(self.frame_forecast)
        self.stackedWidget.addWidget(self.page_forecast_1)
        self.page_forecast_2 = QtWidgets.QWidget()
        self.page_forecast_2.setObjectName("page_forecast_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_forecast_2)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_forecast_2 = QtWidgets.QFrame(self.page_forecast_2)
        self.frame_forecast_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_forecast_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_forecast_2.setObjectName("frame_forecast_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_forecast_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_1km_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_1km_2.setObjectName("label_1km_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_1km_2)
        self.label_3km_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_3km_2.setObjectName("label_3km_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3km_2)
        self.label_5km_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_5km_2.setObjectName("label_5km_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5km_2)
        self.label_10km_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_10km_2.setObjectName("label_10km_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10km_2)
        self.label_halfMarathon_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_halfMarathon_2.setObjectName("label_halfMarathon_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_halfMarathon_2)
        self.label_marathon_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_marathon_2.setObjectName("label_marathon_2")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_marathon_2)
        self.timeEdit_1km_2 = QtWidgets.QTimeEdit(self.frame_forecast_2)
        self.timeEdit_1km_2.setObjectName("timeEdit_1km_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.timeEdit_1km_2)
        self.timeEdit_3km_2 = QtWidgets.QTimeEdit(self.frame_forecast_2)
        self.timeEdit_3km_2.setObjectName("timeEdit_3km_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeEdit_3km_2)
        self.timeEdit_5km_2 = QtWidgets.QTimeEdit(self.frame_forecast_2)
        self.timeEdit_5km_2.setObjectName("timeEdit_5km_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeEdit_5km_2)
        self.timeEdit_10km_2 = QtWidgets.QTimeEdit(self.frame_forecast_2)
        self.timeEdit_10km_2.setObjectName("timeEdit_10km_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timeEdit_10km_2)
        self.timeEdit_halfMarathon_2 = QtWidgets.QTimeEdit(self.frame_forecast_2)
        self.timeEdit_halfMarathon_2.setObjectName("timeEdit_halfMarathon_2")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.timeEdit_halfMarathon_2)
        self.timeEdit_Marathon = QtWidgets.QTimeEdit(self.frame_forecast_2)
        self.timeEdit_Marathon.setObjectName("timeEdit_Marathon")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.timeEdit_Marathon)
        self.label_tips_2 = QtWidgets.QLabel(self.frame_forecast_2)
        self.label_tips_2.setObjectName("label_tips_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_tips_2)
        self.verticalLayout_17.addWidget(self.frame_forecast_2)
        self.stackedWidget.addWidget(self.page_forecast_2)
        self.page_generatePlan = QtWidgets.QWidget()
        self.page_generatePlan.setObjectName("page_generatePlan")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_generatePlan)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_generatePlan = QtWidgets.QFrame(self.page_generatePlan)
        self.frame_generatePlan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_generatePlan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_generatePlan.setObjectName("frame_generatePlan")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_generatePlan)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.timeEdit = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit.setObjectName("timeEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.comboBox = QtWidgets.QComboBox(self.frame_generatePlan)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_5 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.label_2 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.label_6 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.timeEdit_2)
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.timeEdit_3)
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.timeEdit_4)
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.timeEdit_5)
        self.timeEdit_6 = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit_6.setObjectName("timeEdit_6")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.timeEdit_6)
        self.timeEdit_7 = QtWidgets.QTimeEdit(self.frame_generatePlan)
        self.timeEdit_7.setObjectName("timeEdit_7")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.timeEdit_7)
        self.pushButton = QtWidgets.QPushButton(self.frame_generatePlan)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.label_12 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_generatePlan)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.label_13)
        self.verticalLayout_12.addWidget(self.frame_generatePlan)
        self.stackedWidget.addWidget(self.page_generatePlan)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_home.setText(_translate("MainWindow", "首页"))
        self.pushButton_clac.setText(_translate("MainWindow", "计算"))
        self.pushButton_plan.setText(_translate("MainWindow", "计划"))
        self.pushButton_movement.setText(_translate("MainWindow", "动作"))
        self.pushButton_prevent.setText(_translate("MainWindow", "防护"))
        self.label.setText(_translate("MainWindow", "999"))
        self.tableWidget_physical.setSortingEnabled(False)
        item = self.tableWidget_physical.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_physical.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_physical.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_physical.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_physical.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_physical.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_physical.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_physical.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_physical.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_physical.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_sports.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_sports.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_sports.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_sports.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_sports.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_sports.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_sports.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_sports.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        self.pushButton_conversaion.setText(_translate("MainWindow", "速度转换"))
        self.pushButton_forecast.setText(_translate("MainWindow", "成绩预测"))
        self.pushButton_generate_plan.setText(_translate("MainWindow", "开始生成计划"))
        self.label_distance.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">距离</p></body></html>"))
        self.comboBox_distance.setItemText(1, _translate("MainWindow", "1km"))
        self.comboBox_distance.setItemText(2, _translate("MainWindow", "3km"))
        self.comboBox_distance.setItemText(3, _translate("MainWindow", "5km"))
        self.comboBox_distance.setItemText(4, _translate("MainWindow", "10km"))
        self.comboBox_distance.setItemText(5, _translate("MainWindow", "半程马拉松"))
        self.comboBox_distance.setItemText(6, _translate("MainWindow", "马拉松"))
        self.label_time.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">时间</p></body></html>"))
        self.timeEdit_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_speed.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">速度</p></body></html>"))
        self.label_unit.setText(_translate("MainWindow", "单位"))
        self.radioButton_pace.setText(_translate("MainWindow", "配速(min/km)"))
        self.radioButton_hourSpeed.setText(_translate("MainWindow", "时速(km/h)"))
        self.radioButton_lapSpeed.setText(_translate("MainWindow", "圈速(s/400m)"))
        self.label_pace.setText(_translate("MainWindow", "配速"))
        self.label_hourSpeed.setText(_translate("MainWindow", "时速"))
        self.label_lapSpeed.setText(_translate("MainWindow", "圈速"))
        self.pushButton_confirm_convert.setText(_translate("MainWindow", "确认"))
        self.label_tips.setText(_translate("MainWindow", "请确认您最近的最好成绩(没有进行过测试的项目不用填写)"))
        self.label_1km.setText(_translate("MainWindow", "1km"))
        self.timeEdit_1km.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_3km.setText(_translate("MainWindow", "3km"))
        self.timeEdit_3km.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_5km.setText(_translate("MainWindow", "5km"))
        self.timeEdit_5km.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_10km.setText(_translate("MainWindow", "10km"))
        self.timeEdit_10km.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_halfMarathon.setText(_translate("MainWindow", "半马"))
        self.timeEdit_halfMarathon.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_marathon.setText(_translate("MainWindow", "全马"))
        self.timeEdit_marathon.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.pushButton_confirm.setText(_translate("MainWindow", "确认"))
        self.label_1km_2.setText(_translate("MainWindow", "1km"))
        self.label_3km_2.setText(_translate("MainWindow", "3km"))
        self.label_5km_2.setText(_translate("MainWindow", "5km"))
        self.label_10km_2.setText(_translate("MainWindow", "10km"))
        self.label_halfMarathon_2.setText(_translate("MainWindow", "半马"))
        self.label_marathon_2.setText(_translate("MainWindow", "全马"))
        self.timeEdit_1km_2.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_3km_2.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_5km_2.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_10km_2.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_halfMarathon_2.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_Marathon.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.label_tips_2.setText(_translate("MainWindow", "预测结果"))
        self.label_3.setText(_translate("MainWindow", "目标距离"))
        self.label_4.setText(_translate("MainWindow", "目标时间"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.comboBox.setItemText(1, _translate("MainWindow", "1km"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3km"))
        self.comboBox.setItemText(3, _translate("MainWindow", "5km"))
        self.comboBox.setItemText(4, _translate("MainWindow", "10km"))
        self.comboBox.setItemText(5, _translate("MainWindow", "半马"))
        self.comboBox.setItemText(6, _translate("MainWindow", "全马"))
        self.label_5.setText(_translate("MainWindow", "当前能力"))
        self.label_2.setText(_translate("MainWindow", "目标设置"))
        self.label_6.setText(_translate("MainWindow", "1km"))
        self.label_7.setText(_translate("MainWindow", "3km"))
        self.label_8.setText(_translate("MainWindow", "5km"))
        self.label_9.setText(_translate("MainWindow", "10km"))
        self.label_10.setText(_translate("MainWindow", "半马"))
        self.label_11.setText(_translate("MainWindow", "全马"))
        self.timeEdit_2.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_3.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_4.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_5.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_6.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.timeEdit_7.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
